include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  # For more information on DevOps with GNOME technologies, see:
  # https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/DevOps-with-Flatpak
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

.devel-variables:
  variables:
    BUNDLE: "com.maxrdz.Memories.Devel.flatpak"
    MANIFEST_PATH: "com.maxrdz.Memories.Devel.json"
    FLATPAK_MODULE: "memories"
    APP_ID: "com.maxrdz.Memories.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

stages:
  - check
  - build
  - test
  - deploy

i18n:
  image: alpine
  stage: check
  interruptible: true
  script:
    - apk add --no-cache git
    # tldr: If the POTFILES.in isn't up to date, error.
    - sh ./build-aux/generate-potfile.sh
    - git diff --exit-code

cargo-deny:
  image: rust
  stage: check
  interruptible: true
  script:
    - cargo install cargo-deny --locked
    - cargo deny check

cargo-fmt:
  image: 'rust:slim'
  stage: check
  interruptible: true
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check

cargo-clippy:
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master'
  stage: check
  tags:
    - flatpak
  interruptible: true
  script:
    # Report the installed versions of the runtime
    - flatpak info org.gnome.Platform
    - flatpak info org.gnome.Sdk

    # Print the date, since appstream depends on local timezone
    - date && date -u

    - rewrite-flatpak-manifest ${MANIFEST_PATH} ${FLATPAK_MODULE} ${CONFIG_OPTS}
    - flatpak-builder --user --disable-rofiles-fuse --force-clean --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} <<END
        cargo clippy -- -D warnings
      END

cargo-test:
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master'
  stage: check
  tags:
    - flatpak
  interruptible: true
  script:
    # Report the installed versions of the runtime
    - flatpak info org.gnome.Platform
    - flatpak info org.gnome.Sdk

    # Print the date, since appstream depends on local timezone
    - date && date -u

    - rewrite-flatpak-manifest ${MANIFEST_PATH} ${FLATPAK_MODULE} ${CONFIG_OPTS}
    - flatpak-builder --user --disable-rofiles-fuse --force-clean --keep-build-dirs --stop-at=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
    - flatpak build-finish --socket=x11 --share=network flatpak_app
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --user --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH} <<END
        cargo test
      END

flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.devel-variables']
  stage: build
  tags:
    - flatpak
  interruptible: true
  variables:
    RUN_TESTS: "0"
    CONFIG_OPTS: "-Dprofile=devel"

flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.devel-variables']
  stage: build
  tags:
    - flatpak
  interruptible: true
  allow_failure: true
  variables:
    RUN_TESTS: "0"
    CONFIG_OPTS: "-Dprofile=devel"

sast:
  stage: test

nightly@x86_64:
  extends: ".publish_nightly"
  stage: deploy
  tags:
    - flatpak
  needs:
    - flatpak@x86_64

nightly@aarch64:
  extends: ".publish_nightly"
  stage: deploy
  tags:
    - flatpak
  needs:
    - flatpak@aarch64
