[type.po]
extend-glob = ["*.po"]
check-file = false

[type.json]
extend-glob = ["*.json"]
check-file = false

[type.png]
extend-glob = ["*.png"]
check-file = false

# Ignore LEGAL file because it doesn't handle names well.
[type.txt]
extend-glob = ["LEGAL.txt"]
check-file = false

