[type.po]
extend-glob = ["*.po"]
check-file = false

[type.json]
extend-glob = ["*.json"]
check-file = false

[type.png]
extend-glob = ["*.png"]
check-file = false

# False positives from last names in legal sections
[default.extend-words]
Damon = "Damon"
Mena = "Mena"

