[package]
name = "album"
version = "46.1.0"
edition = "2021"
rust-version = "1.77"
license = "GPL-3.0-or-later"
authors = ["Max Rodriguez <me@maxrdz.com>"]
repository = "https://gitlab.gnome.org/maxrdz/Album"
homepage = "https://gitlab.gnome.org/maxrdz/Album"
publish = false

[package.metadata.urls]
issuetracker = "https://gitlab.gnome.org/maxrdz/Album/issues"

[profile.release]
codegen-units = 1 # Best LLVM optimization when built on a single thread
panic = "abort" # Remove unwinding on release
opt-level = 3
lto = true
strip = true

[dependencies]
gdk = { version = "0.8", package = "gdk4", features = ["v4_14"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gio = { version = "0.19", features = ["v2_76"] }
glib-macros = { version = "0.19" }
gtk = { version = "0.8", package = "gtk4", features = ["v4_14"] }
libadwaita = { version = "0.6", features = ["v1_5"] }
log = { version = "0.4" }
pretty_env_logger = { version = "0.5" }
tracing = { version = "0.1.36" }

